export const members = [
  {
    slug: 'abu-ashraf-masnun',
    name: 'Abu Ashraf Masnun',
    role: 'Founder',
    initials: 'AM',
    photo: null,
    bio: 'Building and scaling successful products since 2009. Polyglot developer, passionate about software design and architecture.',
    skills: ['Software Architecture', 'Product Strategy', 'Leadership', 'Business Development', 'System Design'],
    email: 'masnun@tech-m8.solutions',
  },
  {
    slug: 'rumpa-paul',
    name: 'Rumpa Paul',
    role: 'Software Engineer',
    initials: 'RP',
    photo: null,
    bio: 'Rumpa Paul is a frontend developer with strong expertise in building modern, responsive web applications using React. She enjoys turning ideas and feature requirements into smooth, user-friendly digital experiences that are both scalable and easy to maintain.\n\nHer work focuses on integrating APIs with the frontend to create fast, reliable, and efficient applications. She works closely with designers, developers, and other team members to deliver high-quality solutions that meet both business and user needs.\n\nRumpa is passionate about writing clean, well-structured code and thoroughly testing every feature to ensure excellent performance and reliability. She also enjoys exploring new technologies and third-party tools that help improve development speed and create smarter solutions.\n\nWith a strong interest in research and innovation, Rumpa is always looking for better ways to solve challenges and build products that make a real impact.',
    skills: ['React', 'JavaScript', 'API Integration', 'Responsive Design', 'Testing'],
    email: 'masnun@tech-m8.solutions',
  },
  {
    slug: 'sudarshan-mondal',
    name: 'Sudarshan Mondal',
    role: 'Software Engineer',
    initials: 'SM',
    photo: null,
    bio: 'Sudarshan is a passionate software engineer who enjoys solving complex problems and building reliable, high-performing applications. With 3 years of experience in Android development and 2 years working with Django, he has developed a strong ability to create clean, scalable, and efficient software solutions.\n\nHis journey in technology began with Python and later expanded into data science, where he discovered the value of using data to drive smarter decisions and meaningful results. Today, he focuses on developing Django applications, working extensively with Django ORM, Celery, and Redis to build robust and responsive systems.\n\nSudarshan has strong experience with data structures and algorithms, along with solid programming expertise in both Python and Java. He believes great software should not only work well but also be easy to read, maintain, and improve.\n\nAlways eager to learn and grow, Sudarshan approaches every new challenge as an opportunity to sharpen his skills and create better solutions. Outside of work, he enjoys reading and keeping up with the latest developments in technology.',
    skills: ['Django', 'Python', 'Android', 'Django ORM', 'Celery', 'Redis', 'Data Science'],
    email: 'masnun@tech-m8.solutions',
  },
  {
    slug: 'mohsin-al-mamun',
    name: 'Mohsin Al-Mamun',
    role: 'Software Engineer',
    initials: 'MM',
    photo: null,
    bio: 'Mohsin Al-Mamun is a software engineer at TechM8. He specializes in frontend development, building modern and intuitive interfaces that make the platform easy and enjoyable to use.\n\nHis work is centered on creating seamless user experiences through clean, maintainable code and efficient API integrations. Mohsin enjoys transforming ideas into practical solutions that are both visually engaging and technically reliable.\n\nIn addition to development, he also supports project management by helping teams stay organized, aligned, and on schedule. He works closely with designers, developers, and stakeholders to ensure smooth communication and successful delivery of every milestone.\n\nMohsin is also involved in overseeing the QA testing process, helping maintain the platform\'s performance, reliability, and overall quality so users always have the best possible experience.',
    skills: ['Frontend Development', 'React', 'API Integration', 'Project Management', 'QA Testing'],
    email: 'masnun@tech-m8.solutions',
  },
  {
    slug: 'shamima-nasrin',
    name: 'Shamima Nasrin',
    role: 'Junior Software Engineer',
    initials: 'SN',
    photo: null,
    bio: 'Shamima Nasrin is a Junior Software Engineer with a passion for building modern, responsive, and user-friendly web applications. She works mainly with React and JavaScript, and is currently growing her skills in Next.js to create faster and more scalable digital experiences.\n\nShe enjoys transforming ideas into clean and engaging interfaces that are both visually appealing and easy to use. By combining frontend technologies with smooth API integrations, Shamima focuses on building applications that are reliable, efficient, and simple to maintain.\n\nCurious and always willing to learn, she regularly explores new tools, frameworks, and best practices to continue improving her skills. Shamima is dedicated to creating digital products that not only function well but also provide a better experience for the people using them.',
    skills: ['React', 'JavaScript', 'Next.js', 'API Integration', 'Responsive Design'],
    email: 'masnun@tech-m8.solutions',
  },
];
